### ISSUE TITLE
Texturing Error Console Message

### ISSUE THREAD

**Issue by vialofivy** [Kaiserouo/Apex-Legends-Auto-Shader-Blender-Addon#2]
Thanks for the amazing plugin, I am getting this issue: **Version: 3.4.1.**

Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Apex-Legends-Auto-Shader-Blender-Addon-main\menu.py", line 24, in execute
    methods[obj.type](obj, CURRENT_NODEADDER)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Apex-Legends-Auto-Shader-Blender-Addon-main\utils.py", line 89, in shadeMesh
    mesh_name = img_path.name[:img_path.name.rindex('_')]
ValueError: substring not found
bpy.context.space_data.shading.type = 'RENDERED'

![image](https://github.com/Kaiserouo/Apex-Legends-Auto-Shader-Blender-Addon/assets/138264114/9917788e-67c1-4e97-b87d-92880af42732)

**Comment by Kaiserouo** [comment]
I think it's most probably because your filename does not meet my requirement.

The addon require the texture name to be like this: `<model_name>_<texture_name>.<file_type>`
For example, this is the _image directory of the same model as yours (but probably exported way earlier).

![image](https://github.com/Kaiserouo/Apex-Legends-Auto-Shader-Blender-Addon/assets/56215438/1108ea83-3dd4-46ad-8cb1-8d718ad3f5ca)

Note that they always have some kind of model name at the front (e.g. `bloodhound_mythic_v21_pilot_level02_body`), followed by an underscore (`_`), and the texture name (e.g. `albedoTexture`).

If your exported filename looks like a string of random stuff, e.g. `0x4a85a742e8e5dceb.png`, then update your legion version and try to export the texture again. **Make sure that when you import rpak files, type `"common.rpak" "root_lgnd_skins.rpak"` manually, otherwise the files won't be properly named.**

![image](https://github.com/Kaiserouo/Apex-Legends-Auto-Shader-Blender-Addon/assets/56215438/c07997bf-0d60-49ae-980b-2d0403e563e6)

Refer to [Notes](https://github.com/Kaiserouo/Apex-Legends-Auto-Shader-Blender-Addon#notes) for more detail.

**Comment by vialofivy** [comment]
I have updated Legion+ and I did the manual typing of the .rpak, And I still get the "0x96dcd6a4ec60e661.png" file format.
and it still doesnt work sadly.

Could you share your Legion+ settings for exporting?

**Comment by Kaiserouo** [comment]
![image](https://github.com/Kaiserouo/Apex-Legends-Auto-Shader-Blender-Addon/assets/56215438/f301cbb6-a99a-4a69-8d65-c2e029ce55a4)

Legion+ 1.7.0 btw.

If you really really can't make it export properly, you may try using archives on the web as a last resort...
ref. https://biast12.site/Apex_PC_Archive/Legends/Models/Bloodhound/bloodhound_v21_pilot_level02_w/_images/
