### ISSUE TITLE
Titanfall - Shade All

### ISSUE THREAD

**Issue by Ma110w** [Kaiserouo/Apex-Legends-Auto-Shader-Blender-Addon#3]
I was just wondering from you, a developer's, stand point, How difficult would it be to add a "Shade All" button if at all?

**Comment by Kaiserouo** [comment]
I haven't touched this project (or just titanfall models in blender in general) for a long time so the below comments are based on my memory. TLDR, you can do that by selecting all the armatures you wanna shade and use "shade by material name matching (folder)", but the result might not be what you want.



IIRC, titanfall's models don't come with the materials, unlike apex's model. The fact that i can implement "shade all" for apex's model (by selecting all armatures and click shade) is because apex's model auto-imports the albedo texture, from which i can know where everything are.
Titanfall, on the other hand, has quite a few problems:
- the model don't come with any texture, you have to export the the texture in another folder and i can't possibly know where that folder is unless you tell me (by selecting the material folder)
- the material folder name may not match perfectly with the mesh name. This is not a problem in apex because of how consistent they name things for apex's models, materials and textures (and the fact that the albedo texture is auto-imported so i know where the material folder is). This means even if you give me a folder with all the materials in titanfall, i might not found the right material folder for the mesh. I can still try by matching the mesh (or material?) name with the most similar material folder name, and that is what "shade by material matching (folder)" does. there might be errors where the addon shade a material with the wrong material folder, but that is the best i can do. You can always reshade wrong materials with the right material folder one by one tho.

**Comment by Kaiserouo** [comment]
btw, some quirks i forgot to mention
- "shade by material name matching (folder)" should work when you choose mutliple meshes and armatures. this is also the expected behavior with apex's auto-shading function. if it doesn't then that might be a bug.
- i added "shade by material name matching (folder)" after i made that demo video so there's no demo for this function. i do hope the steps and file tree helps with how the procedure works.
- i don't think i have a real case in which the materials are shaded with the wrong material folder, but this may happen in theory. similar name matching isn't perfect.

**Comment by Ma110w** [comment]
Damn, Okay, Well, Is there any good way you know of to import decorations with their coordinates, just asking because the map objects come with coordinates

**Comment by Ma110w** [comment]
like i have been looking for a good way to do the above comment, im even willing to pay!

**Comment by Kaiserouo** [comment]
I've never dealt with map related models in apex and titanfall before (because I can't even import them with the methods in some tutorials on the internet in the first place). I don't have the details and also don't really know if there are more quirks to the coordinate thing you mentioned, so I can't provide more help.
If you know python and can spend some time with the blender api maybe you can translate the meshes to some specific coordinates you want? but i don't really have a need for this, so if you really wanna do this perhaps you can find others that is actually still working with titanfall models now.

**Comment by Ma110w** [comment]
Thank you for giving it some thought. I know that the MPRT importer works with one of the .Cast versions, specifically version 0.90.5, which I use. I had to change two math expressions in the plugin script because they always resulted in an error. However, I don't see it being very useful right now, as decorations become extremely laggy by themselves. Importing them into a map would probably cause Blender to give up.

**Comment by Kaiserouo** [comment]
If you can fix the code in the importer, maybe you can specify what part of the map you wanna import? I'm guessing blender couldn't handle the whole map, but if you only wanna have a scene for screenshots (maybe with a skybox?) you don't have to import the whole map.
Use something like `bpy.types.Panel` to specify what part of the map you wanna import (e.g., x/y boundary), and filter out the meshes out of range in the importer code?
Just a thought though.

**Comment by Ma110w** [comment]
all it was was converting two instances of "//" > "/" by no means am i a programmer lol 😅
